server:
  ssl:    key-store: classpath:mohdasha.com.p12
    key-store-type: PKCS12
    key-store-password: 
    key-alias: mohdasha
spring:  data:    mongodb:      host: localhost
      port: 27017
      database: testdb